* Org-learning 

1. Always train CP with a target. This really helps you to train and read articles(like implementation and algorithms and maths) to reach your target as fast as possible

2. Train with your friends. Training with your friends and trying to out perform them.

3. Always take rating seriously and compete online in many sites. Rating sometimes doesn't mean your real performance. Your real performance sometimes might be worse or better than your rating but it won't be further than +100/-100. If rating was to be taken seriously, you would try your best to solve the problem within the contest and prevent rating loss.

4. Always expect a reward. Even if the reward would take a long time or it would be small, expecting a reward is a really good boost for you to train.

5. Learn new algorithms and data structures. Learning them is very important(for example DFS,segment trees,Dijkstra,etc...). Mathematics is also very important(especially forming equations,number theories,combinatorics,etc...)

6. Don't solve too easy problems. Solving too easy problems won't make you get better. Also, you should solve on the topics you are weak on and solve randomly(random solving problems a little bit higher than your rating is one of the best practicing techniques!)

7. Always try to solve problems you don't get during a real contest. That would teach you new techniques and ideas you missed to think about during the contest!(Suggested by ehnryx)

8. You should like competitive programming. Most of the time if you like a subject, you would be good at it!(Suggested by ehnryx)

9. Check the editorial if you failed. Failing is part of the training. Even if you find that you fail a lot, failure will turn to success after you learn the new ideas/techniques/ways of thinking. Most importantly, you should check the editoral if you failed to solve the current problem.


* Problems: 
- Striver's CP Sheet - Ace Interviews :: https://takeuforward.org/competitive-programming/strivers-cp-sheet
